{{- if .Values.certs.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certs.name }}
  labels:
    {{- include "pmm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
# ngnix ssl certificates
  {{- with .Values.certs.files }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
