{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pmm.serviceAccountName" . }}
  labels:
    {{- include "pmm.labels" . | nindent 4 }}
  {{- $irsa := "" }}
  {{- if and .Values.centralBackupStorage.enabled (eq .Values.centralBackupStorage.mode "s3") }}
  {{- $irsa = .Values.centralBackupStorage.s3.irsaRoleArn }}
  {{- end }}
  {{- if or .Values.serviceAccount.annotations $irsa }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $irsa }}
    eks.amazonaws.com/role-arn: {{ $irsa | quote }}
    {{- end }}
  {{- end }}
{{- end }}
