{{- if index .Values "victoria-metrics-cluster" "vmauth" "enabled" -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.secret.name) }}
{{- $existingData := dict }}
{{- if $existingSecret }}
{{- $existingData = $existingSecret.data }}
{{- end }}
{{- if or .Values.secret.create $existingSecret -}}
{{- $vmuser := get $existingData "VMAGENT_remoteWrite_basicAuth_username" | default (.Values.secret.victoriametrics_user | default "victoriametrics_pmm" | b64enc) | b64dec }}
{{- $vmpass := get $existingData "VMAGENT_remoteWrite_basicAuth_password" | default (.Values.secret.victoriametrics_password | default (randAlphaNum 32) | b64enc) | b64dec }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-victoria-metrics-cluster-vmauth
  namespace: {{ .Release.Namespace }}
  labels:
    app: vmauth
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "pmm.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "pmm.chart" . }}
type: Opaque
stringData:
  auth.yml: |
    users:
    - username: {{ $vmuser | quote }}
      password: {{ $vmpass | quote }}
      url_map:
      - src_paths:
        - "/api/v1/write"
        url_prefix: "http://{{ .Release.Name }}-victoria-metrics-cluster-vminsert.{{ .Release.Namespace }}.svc.cluster.local:8480/insert/1/prometheus/"
      - src_paths:
        - "/api/v1/query"
        - "/api/v1/query_range"
        - "/api/v1/series"
        - "/api/v1/labels"
        - "/api/v1/label/.+/values"
        url_prefix: "http://{{ .Release.Name }}-victoria-metrics-cluster-vmselect.{{ .Release.Namespace }}.svc.cluster.local:8481/select/1/prometheus/"
{{- end }}
{{- end }}

