{{- if and .Values.clusterSync.enabled .Values.clusterSync.source.credentials }}
{{- $username := .Values.clusterSync.source.credentials.username -}}
{{- $password := .Values.clusterSync.source.credentials.password -}}
{{- if or $username $password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-source" (default (printf "%s-sync" (include "psmdb-database.fullname" .)) .Values.clusterSync.name)) .Values.clusterSync.source.credentialsSecret }}
  namespace: {{ include "psmdb-database.namespace" . }}
  labels:
{{ include "psmdb-database.labels" . | indent 4 }}
type: Opaque
stringData:
  username: {{ required "clusterSync.source.credentials.username is required when credentials are inlined" $username | quote }}
  password: {{ required "clusterSync.source.credentials.password is required when credentials are inlined" $password | quote }}
{{- end }}
{{- end }}
