apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-operator-databaseclusterbackup-viewer-role
rules:
- apiGroups:
  - everest.percona.com
  resources:
  - databaseclusterbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - databaseclusterbackups/status
  verbs:
  - get
