apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-operator-databaseclusterrestore-viewer-role
rules:
- apiGroups:
  - everest.percona.com
  resources:
  - databaseclusterrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - databaseclusterrestores/status
  verbs:
  - get
