apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-operator-databasecluster-viewer-role
rules:
- apiGroups:
  - everest.percona.com
  resources:
  - databaseclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - databaseclusters/status
  verbs:
  - get
