apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-operator-databaseengine-viewer-role
rules:
- apiGroups:
  - everest.percona.com
  resources:
  - databaseengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - databaseengines/status
  verbs:
  - get
