---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: everest-operator
    app.kubernetes.io/managed-by: kustomize
  name: enginefeatures.everest-splithorizondnsconfig-viewer-role
rules:
  - apiGroups:
      - enginefeatures.everest.percona.com
    resources:
      - splithorizondnsconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - enginefeatures.everest.percona.com
    resources:
      - splithorizondnsconfigs/status
    verbs:
      - get
