apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: everest-operator-leader-election-rolebinding
  namespace: {{ include  "everest.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: everest-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: everest-operator-controller-manager
  namespace: {{ include  "everest.namespace" .}}
