apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - backupstorages
  - databaseclusterbackups
  - databaseclusterrestores
  - databaseclusters
  - databaseengines
  - dataimportjobs
  - monitoringconfigs
  - podschedulingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - backupstorages/finalizers
  - databaseclusterbackups/finalizers
  - databaseclusterrestores/finalizers
  - databaseclusters/finalizers
  - databaseengines/finalizers
  - dataimportjobs/finalizers
  - monitoringconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - everest.percona.com
  resources:
  - backupstorages/status
  - databaseclusterbackups/status
  - databaseclusterrestores/status
  - databaseclusters/status
  - databaseengines/status
  - dataimportjobs/status
  - monitoringconfigs/status
  - podschedulingpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - everest.percona.com
  resources:
  - dataimporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmagents
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - installplans
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pgv2.percona.com
  resources:
  - perconapgbackups
  - perconapgclusters
  - perconapgrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - postgresclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - psmdb.percona.com
  resources:
  - perconaservermongodbbackups
  - perconaservermongodbrestores
  - perconaservermongodbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxc.percona.com
  resources:
  - perconaxtradbclusterbackups
  - perconaxtradbclusterrestores
  - perconaxtradbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - create
  - delete
  - escalate
  - bind
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch

