apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: everest-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: everest-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: everest-operator-controller-manager
  namespace: {{ include  "everest.namespace" . }}
