apiVersion: v1
kind: Service
metadata:
  name: everest-operator-metrics-service
  namespace: {{ include  "everest.namespace" . }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: everest-operator
  sessionAffinity: None
  type: ClusterIP
