apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-operator-monitoringconfig-viewer-role
rules:
- apiGroups:
  - everest.percona.com
  resources:
  - monitoringconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - monitoringconfigs/status
  verbs:
  - get
