apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: everest-operator
  name: everest-operator-webhook-service
  namespace: {{ include "everest.namespace" . }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: everest-operator