apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: everest-db
  namespace: argocd
spec:
  destination:
    namespace: everest
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: everest-db-namespace
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.3.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

