apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
{{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "postgres-operator.fullname" . }}
{{- if not (or .Values.watchNamespace .Values.watchAllNamespaces) }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
{{ include "postgres-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "postgres-operator.fullname" . }}
  {{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  {{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "postgres-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
