apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.monitoring.namespace }}
  namespace: {{ .Values.monitoring.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.monitoring.namespace }}
  upgradeStrategy: Default
