{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pmm.serviceAccountName" . }}
  namespace: {{ include  "pmm.namespace" . }}
  labels:
    {{- include "pmm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ include "pmm.serviceAccountName" . }}-token
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "pmm.serviceAccountName" . }}-token
  namespace: {{ include  "pmm.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "pmm.serviceAccountName" . }}
{{- end }}
