CREATE DATABASE grafana;
CREATE DATABASE "pmm-managed";

CREATE USER pmmuser WITH SUPERUSER ENCRYPTED PASSWORD 'pmmpass';
CREATE USER gfuser WITH SUPERUSER ENCRYPTED PASSWORD 'gfpass';

GRANT ALL PRIVILEGES ON DATABASE "pmm-managed" TO pmmuser;
GRANT ALL PRIVILEGES  ON DATABASE grafana TO gfuser;

\c pmm-managed
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

