{{- if (ne (include "everest.namespace" .) "everest-system") }}
{{ fail "Namespace cannot be set to anything other than everest-system" }}
{{- end }}
{{- $tlsCertsPath := "/etc/tls" }}
{{- $probeScheme := "HTTP" }}
{{- if .Values.server.tls.enabled }}
{{- $probeScheme = "HTTPS" }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: everest-server
  namespace: {{ include  "everest.namespace" . }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: everest-server
      app.kubernetes.io/component: everest-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: everest-server
        app.kubernetes.io/component: everest-server
    spec:
      serviceAccountName: everest-admin
      automountServiceAccountToken: true
      volumes:
      - name: jwt-secret
        secret:
          secretName: everest-jwt
      {{- if .Values.server.tls.enabled }}
      - name: tls-certs
        secret:
          secretName: {{ .Values.server.tls.secret.name }}
      {{- end }}
      containers:
      - name: everest
        image: {{ .Values.server.image }}:{{ .Chart.Version }}
        ports:
          - containerPort: {{ .Values.server.service.port }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.server.service.port }}
            scheme: {{ $probeScheme }}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.server.service.port }}
            scheme: {{ $probeScheme }}
          initialDelaySeconds: 300
          periodSeconds: 15
        resources: {{ toYaml .Values.server.resources | nindent 12 }}
        volumeMounts:
        - name: jwt-secret
          mountPath: /etc/jwt
        {{- if .Values.server.tls.enabled }}
        - name: tls-certs
          mountPath: {{ $tlsCertsPath }}
          readOnly: true
        {{- end }}
        env:
        {{- if not .Values.telemetry }}
        - name: DISABLE_TELEMETRY
          value: "true"
        {{- end }}
        {{- if hasKey .Values.server "apiRequestsRateLimit" }}
        - name: API_REQUESTS_RATE_LIMIT
          value: "{{ .Values.server.apiRequestsRateLimit }}"
        {{- end }}
        - name: VERSION_SERVICE_URL
          value: {{ (include "everest.versionMetadataURL" .) }}
        - name: PORT
          value: {{ .Values.server.service.port | quote }}
        {{- if .Values.server.tls.enabled }}
        - name: TLS_CERTS_PATH
          value: {{ $tlsCertsPath | quote }}
        {{- end }}
        {{- if .Values.server.env }}
        {{- toYaml .Values.server.env | nindent 8 }}
        {{- end }}
