{{- $secretName := (printf "everest-jwt") -}}
{{- $secret := (lookup "v1" "Secret" (include "everest.namespace" .) $secretName ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: everest-jwt
  namespace: {{ include  "everest.namespace" . }}
data:
  {{- if not $secret }}
  id_rsa: {{ genPrivateKey "rsa" | b64enc  }}
  {{- else }}
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
