{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: "everest-jwt"
  namespace: {{ include  "everest.namespace" . }}
  annotations:
    helm.sh/resource-policy: keep
data:
  id_rsa: {{ .Values.server.jwtKey | default (genPrivateKey "rsa") | b64enc  }}
{{- end }}
