{{- if (and .Release.IsInstall .Values.server.tls.enabled (not .Values.server.tls.certificate.create) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.tls.secret.name }}
  namespace: {{ include  "everest.namespace" . }}
  annotations:
    helm.sh/resource-policy: keep
data: 
  {{- include "everest.tlsCerts" . | trim | nindent 2 }}
{{- end }}
