# Default values for pg-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

operatorImageRepository: docker.io/percona/percona-postgresql-operator
imagePullPolicy: Always
image: ""

# set if you want to specify a namespace to watch
# defaults to `.Release.namespace` if left blank
# watchNamespace:

# set if operator should be deployed in cluster wide mode. defaults to false
watchAllNamespaces: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you don't want to specify resources, comment the following
  # lines and add the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

# disableTelemetry: according to
# https://docs.percona.com/percona-operator-for-postgresql/2.0/telemetry.html
# this is how you can disable telemetry collection
# default is false which means telemetry will be collected
disableTelemetry: false

logStructured: false
logLevel: "INFO"
