# This template checks if all Everest CRDs are up-to-date during a Helm upgrade.
# - It looks for CRDs with the label "everest.percona.com/crd".
# - If no such CRDs are found, it fails the upgrade with an error message. Typically this may only ever happen once, that is, when the chart is upgraded to the
#   first version that includes these new labels on the CRDS.
# - If the CRDs are found but their version (label "everest.percona.com/version") does not match the current chart version, it also fails the upgrade.
# This ensures that CRDs are upgraded before the Helm release is upgraded.

{{- if (and .Release.IsUpgrade .Values.upgrade.crdChecks )}}
{{- $found := false }}
{{- range $index, $crd := (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "" ).items }}
  {{- if (and (hasKey $crd "metadata") (hasKey $crd.metadata "labels") (hasKey $crd.metadata.labels "everest.percona.com/crd")) }}
    {{- if not (hasKey $crd.metadata.labels "everest.percona.com/version") }}
      {{ fail "CRD(s) missing 'everest.percona.com/version' label. Cannot verify version" }}
    {{- end }}
    {{- $found = true }}
    {{- $version := index $crd.metadata.labels "everest.percona.com/version" }}
    {{- if ne $version $.Chart.Version }}
      {{ fail "Ensure that CRDs are upgraded first" }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if not $found }}
  {{ fail "No CRDs with the 'everest.percona.com/crd' annotation were found. Ensure that CRDs are upgraded first." }}
{{- end }}
{{- end }}