apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: database-operators
  namespace: {{ include "db.namespace" . }}
spec:
  targetNamespaces:
  - {{ include "db.namespace" . }} 
  upgradeStrategy: Default

